
workflows:
  ios-testflight:
    name: Build for TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - app_store_connect
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter Setup
        script: |
          flutter doctor -v
          flutter clean
          flutter pub get
      
      - name: Build for TestFlight
        script: |
          flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
      email:
        recipients:
          - michealige080@gmail.com
