workflows:
  ios-device:
    name: Build iOS for iPhone
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups: []
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Flutter Setup
        script: |
          flutter doctor -v
          flutter clean
          flutter pub get
      
      - name: Install iOS Dependencies
        script: |
          cd ios
          pod install --repo-update
      
      - name: Build iOS IPA
        script: |
          flutter build ipa --debug --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - michealige080@gmail.com
