workflows:
  ios-simulator:
    name: Build iOS Simulator
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups: []
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter Setup
        script: |
          flutter doctor -v
          flutter clean
          flutter pub get
      
      - name: Build for iOS Simulator
        script: |
          flutter build ios --simulator --debug
    artifacts:
      - build/ios/iphonesimulator/Runner.app
    publishing:
      email:
        recipients:
          - michealige080@gmail.com
