workflows:
  android-app:
    name: Build Android App
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - android_config
      vars:
        GRADLE_TASK: "assembleDebug"
    scripts:
      - name: Set Gradle wrapper permission
        script: |
          chmod +x ./gradlew
          ls -la gradlew  # Debug: verify permissions
      - name: Build Android APK
        script: |
          ./gradlew $GRADLE_TASK
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - michealige080@gmail.com
