workflows:
  android-app:
    name: Build Android App
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups: []
      flutter: stable  # This is crucial - tells Codemagic it's a Flutter project
    scripts:
      - name: Flutter Setup
        script: |
          flutter doctor -v
          flutter clean
          flutter pub get
      
      - name: Build Android APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - michealige080@gmail.com
